### ISSUE TITLE
Missing jq

### ISSUE THREAD

**Issue by stevefan1999-personal** [joedwards32/CS2#120]
I have a Kubernetes cluster that runs CS2 server using Agones, here's the config for pre.sh/post.sh:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: cs2-launch
  namespace: game
data:
  pre.sh: |
    #!/bin/bash
    STEAM_GSLT_RESPONSE=$(curl -s -X POST -d "key=$STEAM_WEBAPI_KEY&appid=$APPID&memo=$HOSTNAME" https://api.steampowered.com/IGameServersService/CreateAccount/v1)
    # {"response":{"steamid":"<STEAM ID>","login_token":"<GSLT TOKEN>"}}

    export SRCDS_TOKEN=$(echo $STEAM_GSLT_RESPONSE | jq -r .response.login_token)
    export STEAM_GSLT_STEAMID=$(echo $STEAM_GSLT_RESPONSE | jq -r .response.steamid)

    # Find dynamic port from Agones
    export CS2_PORT=""
    while [ -z "$CS2_PORT" ]
    do 
      export CS2_PORT=$(curl -s -H "Content-Type: application/json" -X GET http://localhost:${AGONES_SDK_HTTP_PORT}/gameserver | jq -r '[.status.ports[] | select(.name | startswith("srcds-"))][0].port')
      sleep 1s
    done
  post.sh: |
    #!/bin/bash
    # Just a best effort clean-up action, this is not guaranteed to execute, it is recommended to write a simple script that query and delete expired tokens 
    curl -s -X POST -d "key=$STEAM_WEBAPI_KEY&steamid=$STEAM_GSLT_STEAMID" https://api.steampowered.com/IGameServersService/DeleteAccount/v1
```

Here's the Fleet example:
```yaml
apiVersion: agones.dev/v1
kind: Fleet
metadata:
  name: cs2-example
  namespace: game
spec:
  replicas: 1
  template:
    spec:
      container: cs2
      health:
        disabled: true
        failureThreshold: 30
        initialDelaySeconds: 120
        periodSeconds: 10
      immutableReplicas: 1
      ports:
        - container: cs2
          name: srcds
          portPolicy: Passthrough
          protocol: TCPUDP
      sdkServer:
        grpcPort: 9357
        httpPort: 9358
        logLevel: Info
      template:
        metadata:
          labels:
            game: cs2
        spec:
          volumes:
            - name: script
              configMap:
                name: cs2-launch
                defaultMode: 0500
          containers:
            - volumeMounts:
              - name: script
                mountPath: "/home/steam/cs2-dedicated/pre.sh"
                subPath: pre.sh
              - name: script
                mountPath: "/home/steam/cs2-dedicated/post.sh"
                subPath: post.sh
              image: joedwards32/cs2
              imagePullPolicy: Always
              name: cs2
              command: [sleep]
              args: [infinity]
              env:
                - name: STEAM_WEBAPI_KEY
                  valueFrom:
                    secretKeyRef:
                      name: steam-secret
                      key: webapi-key
                - name: APPID
                  value: "730"
```
However, it seems like `jq` is not in the image, so while the token does create, the tokens cannot be extracted
