### ISSUE TITLE
Starting Container

### ISSUE THREAD

**Issue by jpcapone** [joedwards32/CS2#62]
When I start the container I get the error listed below:

`/mnt/server/cs2/game/cs2.sh: No such file or directory`

here is my compose file

```
`version: "3.7"

services:
  cs2:
    image: soren90/cs2:latest
    container_name: cs2-ds

    environment:
      SERVER_HOSTNAME: "XXXXX"
      RCON_PASSWORD: "XXXXXX" 
      IP: 0.0.0.0 
      PORT: 27015
      GAME_TYPE: 0
      GAME_MODE: 1
      MAP: de_inferno
      MAXPLAYERS: 12
      MAPGROUP: mg_active
      GSLT: XXXXXXXXXXXXXXXXXXXXX
      EXTRAARG: #Extra Launch options

    volumes:
      - /var/lib/docker/volumes/cstrike2:/mnt/server
      
    network_mode: "host"

    restart: unless-stopped
    stdin_open: true
    tty: true
  rconpanel:
    image: soren90/rcon-panel
    ports:
      - "3000:3000"
    restart: unless-stopped`
```

I would appreciate any suggestions.
