### ISSUE TITLE
stdin not working?

### ISSUE THREAD

**Issue by stevefan1999-personal** [joedwards32/CS2#82]
I want to `docker attach` to the container and type some commands, unfortunately that didnt work

**Comment by astravexton** [comment]
How are you running the container? If you're using the `docker run` command you will need to add `-it` (`docker run -dit --name=cs2..`, -i is interactive, -t is TTY) to it so you can attach to it, or edit the `docker-compose.yml` add these 2 lines under the `image:` line:

```yml
version: '3.7'
services:
  cs2-server:
    image: joedwards32/cs2
    stdin_open: true
    tty: true
    ...rest of file
```
